name: Enviar correos encontrados

on: [push]

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repo
      uses: actions/checkout@v3

    - name: Crear archivo con correos
      run: |
        grep -R -E "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-z]{2,}" . > emails.txt || true

    - name: Enviar correo
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_PASS }}
        subject: "Correos encontrados en el an√°lisis"
        body: "Se adjunta archivo con los correos encontrados."
        to: ${{ secrets.EMAIL_TO }}
        from: GitHub Actions
        attachments: emails.txt
